
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 'jaja'
      MYSQL_DATABASE: 'GestionAsignaturasIPC'
      MYSQL_USER: 'manager_test'
      MYSQL_PASSWORD: 'RqoK'
    ports:
      - "3306:3306"
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    # Script de espera
    entrypoint: ["sh", "-c", "until nc -z db 3306; do echo Waiting for MySQL; sleep 20; done; node ./app.js"]

volumes:
  db_data:
